### ISSUE TITLE
html2canvas(...).then is not a function

### ISSUE THREAD

**Issue by yuanye097** [niklasvh/html2canvas#1352]
`var poster = document.querySelector('#poster');
poster.onclick = function() {
    html2canvas(msgImage).then(canvas => {
        var dataUrl = canvas.toDataURL('image/jpeg', 0.9);
        console.log(canvas, '[canvas]');
        shareImage.src = dataUrl;
        generate.style.display = "block";
    });
}`
Click the button in the test environment is normal, but the official environment error, suggesting that "html2canvas (...). Then is not a function"

**Comment by niklasvh** [comment]
Please share an example on jsfiddle, or this is a problem within your environment.

**Comment by korengal** [comment]
Not working for me too.

version : 0.4.1

code : 

```
         html2canvas(inclusions).then(function (canvas) {
                            var data = canvas.toDataURL();
                            var width = canvas.width;
                            var height = canvas.height;
                            var docDefinition = {
                                content: [{
                                    image: data,
                                    width: width,
                                    height: height
                                }]
                            };
                            pdfMake.createPdf(docDefinition).download(name);

                        });
```


Error :
TypeError: html2canvas(...).then is not a function

**Comment by niklasvh** [comment]
@korengal v0.4.1 is ~5 years old and has a different API (without Promises).

**Comment by korengal** [comment]
Ok, I need to work on v0.5.0-beta4 ?

**Comment by niklasvh** [comment]
https://github.com/niklasvh/html2canvas/releases/tag/v1.0.0-alpha.8 is the latest version

**Comment by dev-deepak-soni** [comment]
`testmap.php:85 Uncaught TypeError: html2canvas(...).then is not a function
    at HTMLButtonElement.<anonymous> (testmap.php:85)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)`

**

- My code is

** 
` html2canvas(document.body, {
            "logging": true, //Enable log (use Web Console for get Errors and Warnings)
            "proxy": "html2canvasproxy.php"
        }).then(function(canvas) {
            var img = new Image();
            img.onload = function() {
                img.onload = null;
                document.body.appendChild(img);
            };
            img.onerror = function() {
                img.onerror = null;
                if(window.console.log) {
                    window.console.log("Not loaded image from canvas.toDataURL");
                } else {
                    alert("Not loaded image from canvas.toDataURL");
                }
            };
            img.src = canvas.toDataURL("image/png");
        });`

**Comment by rishcodelib** [comment]
I got the Same Problem but it got Resolved by using the latest version of HTML2Canvas Library 

Click below to download it. 

https://github.com/niklasvh/html2canvas/releases/tag/v1.0.0-alpha.8

**Comment by wrimik** [comment]
This took me forever (at least 10 minutes) to find, so I'm gunna post this everywhere

I'm using html2canvas 1.0.0-rc.6  - if you used the first cdnjs link you're probably using some nonsense 0.4.0 from 2013 or something. 

Good luck everyone

```
      html2canvas($('#canvas'), {
                onrendered: function (canvas) {
                    var canvasImg = canvas.toDataURL("image/jpg");
                    $('#target').html('<img src="'+canvasImg+'" alt="">');
                }
            });
```
