### ISSUE TITLE
TypeError: html2canvas.default is not a function

### ISSUE THREAD

**Issue by crwgregory** [niklasvh/html2canvas#1440]
- [x] You are using the latest [version](https://github.com/niklasvh/html2canvas/releases)
- [x] You are testing using the non-minified version of html2canvas and checked any potential issues reported in the console

### Bug reports:
Simple Call:
```javascript
html2canvas(document.getElementById('passport-questions-form')).then(canvas => {
    // code...
});
```
Is giving me:
`ERROR TypeError: html2canvas_1.default is not a function`

This happened after upgrading Angular cli@1.6.8 from 1.5.0. I assume it might be because there was a TypeScript Update?

 * html2canvas version tested with: alpha.10 
 * Browser & version: chrome:64.0.3282.167 
 * Operating system: windows 10

**Comment by crwgregory** [comment]
Can confirm this is because the update to angular cli 1.6.8

Downgrading back to 1.5.0 seems to be a work around for this issue.

**Comment by CardzMania** [comment]
Happens for me too!

**Comment by 1456118242** [comment]
Happens for me too!

I am on angular/cli: 1.7.2

**Comment by 1456118242** [comment]
@crwgregory

**Comment by 1456118242** [comment]
@niklasvh Help me Thank you very much

**Comment by seyidaniels** [comment]
So how do i go about this erro? I should downgrade my version of angular cli?

**Comment by dbonillao** [comment]
Make sure to import the script under the scripts list in angular-cli.json
"scripts": [
   "../node_modules/html2canvas/dist/html2canvas.min.js"
]

And in the class as:

import * as html2canvas from "html2canvas"

**Comment by seyidaniels** [comment]
Thanks @dbonillao

**Comment by codeepic** [comment]
Thanks @dbonillao !

**Comment by rkinnovit** [comment]
Really awesome @dbonillao  thank you so much.......

**Comment by wduvan** [comment]
for me works, in my file `index.html` import

`<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js"></script>`

**Comment by JEEVANJGA** [comment]
Facing this error for html2canvas version : 1.0.0-rc.3

using with react 15, typescript, along with SPFX framework.
#1440
![image](https://user-images.githubusercontent.com/8213715/58646893-01934200-8324-11e9-9d1c-1bcc6255aa72.png)

@niklasvh , kindly please check why this is happening?

**Comment by tufafa** [comment]
![image](https://user-images.githubusercontent.com/38772780/58789595-1cfe9580-8621-11e9-9ead-a3e7d11a9787.png)
how to fix it ?
angular6 html2canvas@1.0.0-rc.3

**Comment by evilbdef** [comment]
how to fix it ?
using angular7 html2canvas@1.0.0-rc.3

**Comment by Pankaj-Sati** [comment]
Remove "default" word 
Instead of html2canvas.default(div, options){...}
Use html2canvas(div, options){...}

**Comment by evilbdef** [comment]
> Remove "default" word
> Instead of html2canvas.default(div, options){...}
> Use html2canvas(div, options){...}

tried, it didn"t work.
My solution is: 
1.download the source code
2.find index.ts
3.comment out the` export default` line(26)
4.add export to html2canvas directly. line(22)
5. rebuild and publish to myOwn npm

**Comment by dharnen** [comment]
I was able to resolve the 'not a function' error that is throw when trying to call `html2canvas(element, options)`. I have similar setup to @JEEVANJGA, using react 15, typescript, and SPFX. After downloading the @types for the module the index.d.ts file looks like this originally:

`import { CloneOptions } from './dom/document-cloner';
import { ResourceOptions } from './core/cache-storage';
import { RenderOptions } from './render/canvas/canvas-renderer';
export declare type Options = CloneOptions & RenderOptions & ResourceOptions & {
    backgroundColor: string;
    foreignObjectRendering: boolean;
    logging: boolean;
    removeContainer?: boolean;
};
declare const html2canvas: (element: HTMLElement, options?: Partial<Options>) => Promise<HTMLCanvasElement>;
export default html2canvas;
`

If you change the last line to:
`export = html2canvas;`

and import the module like this:
`import * as html2canvas from 'html2canvas';`

it no longer throws an error.

Hope this helps someone.

**Comment by uttahb** [comment]
Got the same issue, @dharnen solution helped.

**Comment by bmvr** [comment]
thank you @uttahb.
Worked for me.

**Comment by briancaldass** [comment]
> Pude resolver el error 'no es una función' que se produce al intentar llamar `html2canvas(element, options)`. Tengo una configuración similar a @JEEVANJGA , usando react 15, typecript y SPFX. Después de descargar los @types para el módulo, el archivo index.d.ts tiene este aspecto originalmente:
> 
> `import { CloneOptions } from './dom/document-cloner';`
> `import { ResourceOptions } from './core/cache-storage';`
> `import { RenderOptions } from './render/canvas/canvas-renderer';`
> `export declare type Options = CloneOptions & RenderOptions & ResourceOptions & {`
> ` backgroundColor: string;`
> ` foreignObjectRendering: boolean;`
> ` logging: boolean;`
> ` removeContainer?: boolean;`
> `};`
> `` declare const html2canvas: (element: HTMLElement, options?: Partial<Options>) => ``Promise<HTMLCanvasElement>; ``
> `export default html2canvas;`
> 
> Si cambia la última línea a:
> `export = html2canvas;`
> 
> e importa el módulo así:
> `import * as html2canvas from 'html2canvas';`
> 
> ya no arroja un error.
> 
> Espero que esto ayude a alguien.

But this is wrong, you can not modify the library because at the time of making npm install or update is overwritten the change made or not? or where do you make the change?

**Comment by dharnen** [comment]
Hello @briancaldass,

Modifying the downloaded packages is definitely not a preferred solution because of the risk that if the packages get re downloaded the changes made do not persist, which you touched on. That being said once downloaded they are not overwritten, even if you run npm install, as long as your `package-lock.json` has not been deleted. To relieve the headache of remembering what was changed I created a power shell script that goes into any package I've had to adjust and makes the specified changes. I run this script once after making a branch, or cloning the repo, and installing the packages the first time. Although this is not the best way to handle things it's work for me when handling small errors I've encountered, like the one in this thread.

**Comment by DanLatimer** [comment]
For me the problem was I'm using TypeScript and the `node_modules\html2canvas\dist\types\index.d.ts` file is incorrect. It says that they are exporting html2canvas as the default export `export default html2canvas;`. This is untrue.

I had to use any to get around this as follows:
```
import * as html2canvasWrong from "html2canvas"
var html2canvas = html2canvasWrong as any as (element: HTMLElement, options?: Partial<html2canvasWrong.Options>) => Promise<HTMLCanvasElement>
```

**Comment by Remusqs1** [comment]
> For me the problem was I'm using TypeScript and the `node_modules\html2canvas\dist\types\index.d.ts` file is incorrect. It says that they are exporting html2canvas as the default export `export default html2canvas;`. This is untrue.
> 
> I had to use any to get around this as follows:
> 
> ```
> import * as html2canvasWrong from "html2canvas"
> var html2canvas = html2canvasWrong as any as (element: HTMLElement, options?: Partial<html2canvasWrong.Options>) => Promise<HTMLCanvasElement>
> ```

This worked for me, thanks!
