### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by KinG-InFeT** [niklasvh/html2canvas#1859]
```
Uncaught (in promise) DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
```

### Specifications:

 * html2canvas version tested with: 1.0.0-rc.2
 * Browser & version: chromium latest release
 * Operating system: fedora 29

**Comment by niklasvh** [comment]
Please share an example html/css to replicate the issue

**Comment by code-viper** [comment]
I have this same issue.  My scenario is an iframe without a height and width attribute it would throw this error.  Height and width set in a style tag was ignored.

**Comment by code-viper** [comment]
I found that setting the width/height below fixes the iframe issue with no width/height attributes.

                        case 12:
                            if (!(container instanceof IFrameElementContainer && container.tree)) return [3 /*break*/, 14];
                            iframeRenderer = new CanvasRenderer({
                                id: this.options.id,
                                scale: this.options.scale,
                                backgroundColor: container.backgroundColor,
                                x: 0,
                                y: 0,
                                scrollX: 0,
                                scrollY: 0,
                                width: **container.bounds.width**,
                                height: **container.bounds.height**,
                                cache: this.options.cache,
                                windowWidth: **container.bounds.width**,
                                windowHeight: **container.bounds.height**
                            });
                            return [4 /*yield*/, iframeRenderer.render(container.tree)];
                        case 13:
                            canvas = _b.sent();
                            this.ctx.drawImage(canvas, 0, 0, container.bounds.width, **container.bounds.height**, container.bounds.left, container.bounds.top, container.bounds.width, container.bounds.height);
                            _b.label = 14;

**Comment by KinG-InFeT** [comment]
Hi, i have another issue, white image when take imave from google maps and datatable

**Comment by surojmaharjan** [comment]
I am having similar issue in my form. When I have checkbox field, I get the error
Uncaught (in promise) DOMException: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

The checkbox type form field is 
<input id="test" class="required" name="test" type="checkbox" value="1" required>

**Comment by josephmisiti** [comment]
I'm having the same issue with an iframe, and this PR fixed it for me:

https://github.com/niklasvh/html2canvas/pull/1863/files

**Comment by danielloynaz** [comment]
Hi, 
I'm having the same error. I have checked the previous version and it works fine on "1.0.0-rc.1" for all version above I'm getting the error.

**Comment by srobledo** [comment]
Samething here

**Comment by luyu1314** [comment]
I'm having the same error  on "1.0.0-rc.3"

if use previous version  of  "1.0.0-rc.1", it is  fine

**Comment by falget** [comment]
Hi, i'm having the same error on "1.0.0-rc.3" when html have css: "background: linear-gradient()"

**Comment by Mr-Kapok** [comment]
I'm having the same error on 1.0.0-rc.1 +
when hav css "background-image"

**Comment by shaji-Dev** [comment]
I'm have the same issue:

```
html2canvas(document.getElementById('mapWrapper'), {
      useCORS: true,
      allowTaint: false
    }).then(canvas => {
      const url = canvas.toDataURL('image/png');
      saveAs(url, 'image.jpg');
      window.URL.revokeObjectURL(url);
    });
```

I get this error:
```core.js:6014 ERROR Error: Uncaught (in promise): InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
Error: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at CanvasRenderer.<anonymous> (html2canvas.js:6289)
    at step (html2canvas.js:83)
    at Object.next (html2canvas.js:64)
    at fulfilled (html2canvas.js:54)
    at ZoneDelegate.invoke (zone-evergreen.js:365)
    at Object.onInvoke (core.js:39698)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:851
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:39679)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
    at invokeTask (zone-evergreen.js:485)
    at ZoneTask.invoke (zone-evergreen.js:470)```

**Comment by rdpatel3996** [comment]
I am also facing the same issue as @shaji-Dev , when trying to capture google maps. Any updates here?

**Comment by shaji-Dev** [comment]
@rdpatel3996 Yes, I just needed to add the ignoreElements configuration and all is well, appearently the new version of Google Maps use iframe elements inside which makes it impossible to capture.

```
const mapWrapper = document.getElementById('mapWrapper');
      html2canvas(mapWrapper, {
        useCORS: true,
        allowTaint: false,
        logging: isDevMode(),
        ignoreElements: (node) => {
          return node.nodeName === 'IFRAME';
        }
      }).then(canvas => {
        canvas.toBlob(blob => {
          resolve(blob);
        });
      }).catch(reject);
```

The key is to add this config:
```
ignoreElements: (node) => {
          return node.nodeName === 'IFRAME';
        }
```

**Comment by klues** [comment]
I got the similar error `InvalidStateError: CanvasRenderingContext2D.createPattern: Passed-in canvas has width 0` which only occurs in Firefox. After some investigation I found out it occurs on svg-images set as background-image.

See [this jsfiddle](http://jsfiddle.net/fy3grw94/) for demo.

Including the lines
```
ignoreElements: (node) => {
    return node.style['background-image'].indexOf('image/svg') !== -1;
}
```
is a quickfix.

**Comment by JosefB-FA** [comment]
> I got the similar error `InvalidStateError: CanvasRenderingContext2D.createPattern: Passed-in canvas has width 0` which only occurs in Firefox. After some investigation I found out it occurs on svg-images set as background-image.
> 
> See [this jsfiddle](http://jsfiddle.net/fy3grw94/) for demo.
> 
> Including the lines
> 
> ```
> ignoreElements: (node) => {
>     return node.style['background-image'].indexOf('image/svg') !== -1;
> }
> ```
> 
> is a quickfix.

I have the same issue, but I have the problem that the SVG background image is in a CSS pseudo element :before. Since those are not real DOM nodes, they will not be checked here but also cause the same error, only on Firefox. I came up with the following quickfix for that case:
```
html2canvas(document.body, {
	ignoreElements: (node) => {
		var stylesBefore = window.getComputedStyle(
			node, ':before'
		);
		var stylesAfter = window.getComputedStyle(
			node, ':after'
		);
		var stylesFirstLetter = window.getComputedStyle(
			node, ':first-letter'
		);
		var stylesFirstLine = window.getComputedStyle(
			node, ':first-line'
		);
		var stylesSelection = window.getComputedStyle(
			node, ':selection'
		);
		return stylesBefore['backgroundImage'].indexOf('.svg') !== -1 ||
			stylesAfter['backgroundImage'].indexOf('.svg') !== -1 ||
			stylesFirstLetter['backgroundImage'].indexOf('.svg') !== -1 ||
			stylesFirstLine['backgroundImage'].indexOf('.svg') !== -1 ||
			stylesSelection['backgroundImage'].indexOf('.svg') !== -1;
	}
})
```

**Comment by delewis13** [comment]
Hello,

Thanks for this fantastic library! I am observing this issue in v1.0.0-rc.5

The trigger condition is slightly different than observed by others in this thread however, as it is only observed when the browser is ZOOMED OUT [i.e. window.devicePixelRatio < 1], though the exact zoom level at which it triggers appears to vary [unsure why]. I can consistently reproduce error @ 67% zoom level.

Looking through the stack trace a little, I notice that one of my children elements is pushed to `stackingContext.nonInlineLevel`, and when its height is later evaluated via bounds, `height < 1` [e.g. `0.984` @ 67% zoom], which gets floored to `0`. This is in contrast to either 100% zoom level or higher [i.e. window.devicePixelRatio >= 1], where `height = 1`.

**Comment by Nick-QI** [comment]
me too. this is my solution
``` javascript
   ignoreElements: (el) => {
          const { height } = el.getBoundingClientRect();
          const IGNORE_NODE = ['HEAD','STYLE','META', 'TITLE', 'LINK']
          return el.id === "hide" || (!height && !IGNORE_NODE.some(t => t ===el.nodeName));
        }
```

**Comment by wuniversales** [comment]
I have the same error, I don't know how to fix it...
```
function descargaPDF() {
    var HTML_Width = $(".factura").width();
    var HTML_Height = $(".factura").height();
    var top_left_margin = 15;
    var PDF_Width = HTML_Width + (top_left_margin * 2);
    var PDF_Height = (PDF_Width * 1.5) + (top_left_margin * 2);
    var canvas_image_width = HTML_Width;
    var canvas_image_height = HTML_Height;

    var totalPDFPages = Math.ceil(HTML_Height / PDF_Height) - 1;

    html2canvas($(".factura")[0]).then(function (canvas) {
        var imgData = canvas.toDataURL("image/jpeg", 1.0);
        var pdf = new jsPDF('p', 'pt', [PDF_Width, PDF_Height]);
        pdf.addImage(imgData, 'JPG', top_left_margin, top_left_margin, canvas_image_width, canvas_image_height);
        for (var i = 1; i <= totalPDFPages; i++) { 
            pdf.addPage(PDF_Width, PDF_Height);
            pdf.addImage(imgData, 'JPG', top_left_margin, -(PDF_Height*i)+(top_left_margin*4),canvas_image_width,canvas_image_height);
        }
        pdf.save("Factura.pdf");
        $(".factura").hide();
    });
}
```

**Comment by MichaelLangbein** [comment]
Just as a side-note for those who are having issues with capturing maps (@shaji-Dev , @rdpatel3996, @KinG-InFeT): another thing to consider when you have issues painting a map on a canvas is cross-origin policy. 
A canvas will be tainted by images from another origin than the one your site is being served from. You can check if the map-server allows for CORS by setting the  Access-Control-Allow-Origin header. I'm not sure if this is still a thing, but you might also have to set a crossorigin-attribute on your canvas (though honestly I'd have to google that a little more...)

But this is of course no solution to the svg-issue.

**Comment by pla1** [comment]
I removed a horizontal rule tag with the closing slash `<hr />` that was causing this error.

**Comment by niklasvh** [comment]
Fixed with https://github.com/niklasvh/html2canvas/pull/2409
